services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: admin
      PASSWORD: 1254321
    ports:
      - "9543:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local